steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/home-cleaning-373216/cleanmyplace-artifact/clean-my-place:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/home-cleaning-373216/cleanmyplace-artifact/clean-my-place']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['compute', 'instances', 'create-with-container', 'cleanmyplace-app-eu-w2', '--container-image', 'europe-west1-docker.pkg.dev/home-cleaning-373216/cleanmyplace-artifact/clean-my-place']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=europe-west1'
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-d'